{{- if .Values.envoy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-envoy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloud-native-sre-platform.labels" . | nindent 4 }}
    app.kubernetes.io/name: envoy
spec:
  replicas: {{ .Values.envoy.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: envoy
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "cloud-native-sre-platform.labels" . | nindent 8 }}
        app.kubernetes.io/name: envoy
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: envoy-config
          configMap:
            name: {{ .Release.Name }}-envoy-config
        - name: tmp
          emptyDir: {}
      containers:
        - name: envoy
          image: "{{ .Values.envoy.image.repository }}:{{ .Values.envoy.image.tag }}"
          imagePullPolicy: {{ .Values.envoy.image.pullPolicy }}
          command:
            - /usr/local/bin/envoy
          args:
            - -c
            - /etc/envoy/envoy.yaml
            - --service-cluster
            - cloud-native-sre-platform-envoy
          ports:
            - name: http
              containerPort: 10000
              protocol: TCP
            - name: admin
              containerPort: 9901
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ready
              port: admin
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: admin
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.envoy.resources | nindent 12 }}
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy
              readOnly: true
            - name: tmp
              mountPath: /tmp
{{- end }}
