{{- if .Values.payments.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-payments-hpa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloud-native-sre-platform.labels" . | nindent 4 }}
    app.kubernetes.io/name: payments
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-payments
  minReplicas: {{ .Values.payments.hpa.minReplicas }}
  maxReplicas: {{ .Values.payments.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.payments.hpa.targetCPUUtilizationPercentage }}
{{- end }}
