{{- if .Values.api.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-api-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloud-native-sre-platform.labels" . | nindent 4 }}
    app.kubernetes.io/name: api
spec:
  minAvailable: {{ .Values.api.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: api
{{- end }}
