{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    release: {{ .Values.monitoring.releaseLabel | quote }}
    app.kubernetes.io/part-of: cloud-native-sre-platform
spec:
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: api
      app.kubernetes.io/instance: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.monitoring.scrapeInterval }}
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-payments
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    release: {{ .Values.monitoring.releaseLabel | quote }}
    app.kubernetes.io/part-of: cloud-native-sre-platform
spec:
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: payments
      app.kubernetes.io/instance: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.monitoring.scrapeInterval }}
      scrapeTimeout: 10s
---
{{- if .Values.envoy.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-envoy
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    release: {{ .Values.monitoring.releaseLabel | quote }}
    app.kubernetes.io/part-of: cloud-native-sre-platform
spec:
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: envoy
      app.kubernetes.io/instance: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: admin
      path: /stats/prometheus
      interval: {{ .Values.monitoring.scrapeInterval }}
      scrapeTimeout: 10s
{{- end }}
{{- end }}
